let choices = [];

// 3-star choices
choices[3] = [
	"Dull Blade",
];

// 4-star choices
choices[4] = [
	"Amber",
	"Barbara",
	"Beidou",
	"Bennett",
	"Chongyun",
	"Collei",
	"Diona",
	"Dori",
	"Faruzan",
	"Fischl",
	"Gorou",
	"Kaeya",
	"Kujou Sara",
	"Kuki Shinobu",
	"Layla",
	"Lisa",
	"Ningguang",
	"Noelle",
	"Razor",
	"Rosaria",
	"Sayu",
	"Shikanoin Heizou",
	"Sucrose",
	"Thoma",
	"Xiangling",
	"Xingqiu",
	"Xinyan",
	"Yanfei",
	"Yun Jin",
];

// 5-star choices
choices[5] = [
	"Albedo",
	"Aloy",
	"Arataki Itto",
	"Cyno",
	"Diluc",
	"Eula",
	"Ganyu",
	"Hu Tao",
	"Jean",
	"Kaedehara Kazuha",
	"Kamisato Ayaka",
	"Kamisato Ayato",
	"Keqing",
	"Klee",
	"Mona",
	"Nahida",
	"Nilou",
	"Qiqi",
	"Raiden Shogun",
	"Sangonomiya Kokomi",
	"Shenhe",
	"Tartaglia",
	"Tighnari",
	"Lumine",
	"Aether",
	"Venti",
	"Wanderer",
	"Xiao",
	"Yae Miko",
	"Yelan",
	"Yoimiya",
	"Zhongli",
];




let elementDictionary = {
	"Dull Blade": "LUL",
	"Amber": "Pyro",
	"Barbara": "Hydro",
	"Beidou": "Electro",
	"Bennett": "Pyro",
	"Chongyun": "Cryo",
	"Collei": "Dendro",
	"Diona": "Cryo",
	"Dori": "Electro",
	"Faruzan": "Anemo",
	"Fischl": "Electro",
	"Gorou": "Geo",
	"Kaeya": "Cryo",
	"Kujou Sara": "Electro",
	"Kuki Shinobu": "Electro",
	"Layla": "Cryo",
	"Lisa": "Electro",
	"Ningguang": "Geo",
	"Noelle": "Geo",
	"Razor": "Electro",
	"Rosaria": "Cryo",
	"Sayu": "Anemo",
	"Shikanoin Heizou": "Anemo",
	"Sucrose": "Anemo",
	"Thoma": "Pyro",
	"Xiangling": "Pyro",
	"Xingqiu": "Hydro",
	"Xinyan": "Pyro",
	"Yanfei": "Pyro",
	"Yun Jin": "Geo",
	"Albedo": "Geo",
	"Aloy": "Cryo",
	"Arataki Itto": "Geo",
	"Cyno": "Electro",
	"Diluc": "Pyro",
	"Eula": "Cryo",
	"Ganyu": "Cryo",
	"Hu Tao": "Pyro",
	"Jean": "Anemo",
	"Kaedehara Kazuha": "Anemo",
	"Kamisato Ayaka": "Cryo",
	"Kamisato Ayato": "Hydro",
	"Keqing": "Electro",
	"Klee": "Pyro",
	"Mona": "Hydro",
	"Nahida": "Dendro",
	"Nilou": "Hydro",
	"Qiqi": "Cryo",
	"Raiden Shogun": "Electro",
	"Sangonomiya Kokomi": "Hydro",
	"Shenhe": "Cryo",
	"Tartaglia": "Hydro",
	"Tighnari": "Dendro",
	"Lumine": "Anemo",
	"Aether": "Geo",
	"Venti": "Anemo",
	"Wanderer": "Anemo",
	"Xiao": "Anemo",
	"Yae Miko": "Electro",
	"Yelan": "Hydro",
	"Yoimiya": "Pyro",
	"Zhongli": "Geo",
};



let dullBlades = [
	"Mjolnir",
	"qtip",
	"toothbrush",
	"chainsaw",
	"electricfan",
	"wreckedcar",
];
