let choices = [];

// 3-star choices
choices[3] = [
	{name: "Dull Blade", element: "LUL"},
];

// 4-star choices
choices[4] = [
	{name: "Amber", element: "Pyro"},
	{name: "Barbara", element: "Hydro"},
	{name: "Beidou", element: "Electro"},
	{name: "Bennett", element: "Pyro"},
	{name: "Charlotte", element: "Cryo"},
	{name: "Chevreuse", element: "Pyro"},
	{name: "Chongyun", element: "Cryo"},
	{name: "Collei", element: "Dendro"},
	{name: "Diona", element: "Cryo"},
	{name: "Dori", element: "Electro"},
	{name: "Faruzan", element: "Anemo"},
	{name: "Fischl", element: "Electro"},
	{name: "Freminet", element: "Cryo"},
	{name: "Gaming", element: "Pyro"},
	{name: "Gorou", element: "Geo"},
	{name: "Kaeya", element: "Cryo"},
	{name: "Kaveh", element: "Dendro"},
	{name: "Kirara", element: "Dendro"},
	{name: "Kujou Sara", element: "Electro"},
	{name: "Kuki Shinobu", element: "Electro"},
	{name: "Layla", element: "Cryo"},
	{name: "Lisa", element: "Electro"},
	{name: "Mika", element: "Cryo"},
	{name: "Ningguang", element: "Geo"},
	{name: "Noelle", element: "Geo"},
	{name: "Razor", element: "Electro"},
	{name: "Rosaria", element: "Cryo"},
	{name: "Sayu", element: "Anemo"},
	{name: "Shikanoin Heizou", element: "Anemo"},
	{name: "Sucrose", element: "Anemo"},
	{name: "Thoma", element: "Pyro"},
	{name: "Xiangling", element: "Pyro"},
	{name: "Xingqiu", element: "Hydro"},
	{name: "Xinyan", element: "Pyro"},
	{name: "Yanfei", element: "Pyro"},
	{name: "Yaoyao", element: "Dendro"},
	{name: "Yun Jin", element: "Geo"},
];

// 5-star choices
choices[5] = [
	{name: "Aether", element: "Anemo"},
	{name: "Albedo", element: "Geo"},
	{name: "Alhaitham", element: "Dendro"},
	{name: "Aloy", element: "Cryo"},
	{name: "Arataki Itto", element: "Geo"},
	{name: "Arlecchino", element: "Pyro"},
	{name: "Baizhu", element: "Dendro"},
	{name: "Chiori", element: "Geo"},
	{name: "Cyno", element: "Electro"},
	{name: "Dehya", element: "Pyro"},
	{name: "Diluc", element: "Pyro"},
	{name: "Eula", element: "Cryo"},
	{name: "Furina", element: "Hydro"},
	{name: "Ganyu", element: "Cryo"},
	{name: "Hu Tao", element: "Pyro"},
	{name: "Jean", element: "Anemo"},
	{name: "Kaedehara Kazuha", element: "Anemo"},
	{name: "Kamisato Ayaka", element: "Cryo"},
	{name: "Kamisato Ayato", element: "Hydro"},
	{name: "Keqing", element: "Electro"},
	{name: "Klee", element: "Pyro"},
	{name: "Lumine", element: "Anemo"},
	{name: "Lyney", element: "Pyro"},
	{name: "Mona", element: "Hydro"},
	{name: "Nahida", element: "Dendro"},
	{name: "Navia", element: "Geo"},
	{name: "Neuvillette", element: "Hydro"},
	{name: "Nilou", element: "Hydro"},
	{name: "Qiqi", element: "Cryo"},
	{name: "Raiden Shogun", element: "Electro"},
	{name: "Sangonomiya Kokomi", element: "Cryo"},
	{name: "Shenhe", element: "Cryo"},
	{name: "Tartaglia", element: "Hydro"},
	{name: "Tighnari", element: "Dendro"},
	{name: "Venti", element: "Anemo"},
	{name: "Wanderer", element: "Anemo"},
	{name: "Wriothesley", element: "Cryo"},
	{name: "Xianyun", element: "Anemo"},
	{name: "Xiao", element: "Anemo"},
	{name: "Yae Miko", element: "Electro"},
	{name: "Yelan", element: "Hydro"},
	{name: "Yoimiya", element: "Pyro"},
	{name: "Zhongli", element: "Geo"},
];




let dullBlades = [
	"Mjolnir",
	"qtip",
	"toothbrush",
	"chainsaw",
	"electricfan",
	"wreckedcar",
];
